version: "5"

services:
  mysqlimage:
    image: mysql:8.0.13
    container_name: "Mysqldatabase"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mydatabase
    expose:
      - 3308
    ports:
      - "3308:3306"
  dockercomposeimage:
    image: dockercomposeimage
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "TestApp"
    environment:
      MYSQLDB_HOST: Mysqldatabase
      MYSQLDB_USER: root
      MYSQLDB_PASSWORD: root1234
      MYSQLDB_PORT: 3306
    expose:
      - 8091
    ports:
      - "8091:8080"
    links:
      - mysqlimage